services:
  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - planner_network
    ports:
      - "8080:8080"
    depends_on:
      - psql_db
      - redis_db
    env_file:
      - ../apps/api

  app:
    build:
      context: ../apps/app
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - planner_network
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - ../apps/app

  nginx:
    build:
      context: ../apps/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - planner_network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    env_file:
      - ../apps/nginx

networks:
  planner_network:
    driver: bridge
