server:
  host: "localhost"
  port: "8080"
  mode: "debug"

logger:
  level:  "debug"
  format: "json"

psql_db:
  type:    "postgres"
  host:    "localhost"
  port:    "5432"
  dbname:  "infralyra_db"
  sslmode: "disable"

redis_db:
  host: "localhost"
  port: "6379"
  db: 0

auth:
  access_token_ttl: "15m"
  refresh_token_ttl: "168h"
  rate_limit_count: 20
  rate_limit_ttl: "1m"

interfaces:
  save_ttl: "6h"