services:
  psql_db:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - planner_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: >-
        --set=api.default_user_name=${POSTGRES_DEFAULT_USER}
        --set=api.default_user_login=${POSTGRES_DEFAULT_LOGIN}
        --set=api.default_user_role=${POSTGRES_DEFAULT_ROLE}
        --set=api.default_user_pass=${POSTGRES_DEFAULT_PASS}
    ports:
      - '5432:5432'
    env_file:
      - .env

  redis_db:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - planner_network
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

networks:
  planner_network:
    driver: bridge
