services:
  personal_computer:
    build:
      context: ./test/user-defined-devices/personal-computer
      dockerfile: Dockerfile
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - ./test/user-defined-devices/personal-computer/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.2
    depends_on:
      main:
        condition: service_healthy

  laptop:
    build:
      context: ./test/user-defined-devices/laptop
      dockerfile: Dockerfile
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - ./test/user-defined-devices/laptop/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.3
    depends_on:
      main:
        condition: service_healthy

  mobile_phone:
    build:
      context: ./test/user-defined-devices/mobile-phone
      dockerfile: Dockerfile
    env_file:
      - ./test/user-defined-devices/mobile-phone/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.4
    depends_on:
      main:
        condition: service_healthy

  iot_device:
    build:
      context: ./test/user-defined-devices/iot-device
      dockerfile: Dockerfile
    env_file:
      - ./test/user-defined-devices/iot-device/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.5
    depends_on:
      main:
        condition: service_healthy

  printer:
    build:
      context: ./test/peripheral-devices/printer
      dockerfile: Dockerfile
    env_file:
      - ./test/peripheral-devices/printer/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.6
    depends_on:
      main:
        condition: service_healthy

  scanner:
    build:
      context: ./test/peripheral-devices/scanner
      dockerfile: Dockerfile
    env_file:
      - ./test/peripheral-devices/scanner/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.7
    depends_on:
      main:
        condition: service_healthy

  file_server:
    build:
      context: ./test/service-devices/file-server
      dockerfile: Dockerfile
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - ./test/service-devices/file-server/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.8
    depends_on:
      main:
        condition: service_healthy

  web_server:
    build:
      context: ./test/service-devices/web-server
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.9
    depends_on:
      main:
        condition: service_healthy

  remote_access_server:
    build:
      context: ./test/service-devices/remote-access-server
      dockerfile: Dockerfile
    cap_add:
      - NET_BIND_SERVICE
    env_file:
      - ./test/service-devices/remote-access-server/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.10
    depends_on:
      main:
        condition: service_healthy

  main:
    build:
      context: ./main
      dockerfile: Dockerfile.test
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    env_file:
      - ./main/.env
    restart: unless-stopped
    networks:
      test_network:
        ipv4_address: 192.168.103.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "docker ps --filter name=api-1 --filter status=running -q | grep -q . || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 300s

networks:
  test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.103.0/24
