services:
  psql_db:
    image: postgres:latest
    restart: unless-stopped
    networks:
      - planner_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    env_file:
      - .env

  redis_db:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - planner_network
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

networks:
  planner_network:
    driver: bridge
