FROM docker:24.0.5-dind

RUN apk add --no-cache python3 py3-pip bash git curl

RUN pip3 install docker-compose

WORKDIR /server

COPY ./apps/ .
COPY ./.env .
COPY ./docker-compose.test.yml .

CMD ["docker-compose", "-f", "docker-compose.test.yml", "up", "--build"]
