FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    bash \
    curl \
    git \
    iputils-ping \
    net-tools \
    iptables \
    openssh-client \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://get.docker.com | \
    sh -s -- --channel stable --version 24.0.5

RUN curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/bin/docker-compose && \
  chmod +x /usr/local/bin/docker-compose

RUN useradd -m -s /bin/bash infralyra && \
    echo "infralyra ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /infralyra

COPY ./apps/ ./apps/
COPY ./docker/ ./docker/
COPY ./.env ./.env
COPY ./docker-compose.test.yaml ./docker-compose.test.yaml

CMD ["docker-compose", "-f", "docker-compose.test.yaml", "up", "--build"]
