FROM docker:24.0.5-dind

RUN apk add --no-cache python3 bash git curl

RUN curl -L "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/bin/docker-compose && \
  chmod +x /usr/local/bin/docker-compose

WORKDIR /infralira

COPY ./apps/ .
COPY ./docker/ .
COPY ./.env .
COPY ./docker-compose.test.yaml .

CMD ["docker-compose", "-f", "docker-compose.test.yaml", "up", "--build"]
