events {
    worker_connections 1024;
}

http {
    # Настройки для проксирования
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;

    # HTTP сервер - редирект на HTTPS
    server {
        listen 80;
        server_name localhost;

        return 301 https://$server_name$request_uri;
    }

    server {
        listen 443;
        server_name localhost;

        # Прокси для API
        location /api/ {
            proxy_read_timeout 1m;
            proxy_connect_timeout 1m;
            proxy_send_timeout 1m;

            # Убираем /api/ из URL перед проксированием
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://api:3000/;

            # Дополнительные заголовки для API
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
        }

        # WebSocket для Socket.IO
        location /socket.io/ {
            proxy_http_version 1.1;
            proxy_redirect off;

            proxy_pass http://ws:7000/socket.io/;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-NginX-Proxy false;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_read_timeout 360s;
            proxy_connect_timeout 360s;
            proxy_send_timeout 360s;
        }

        # WebSocket для клиентского приложения
        location /ws/ {
            proxy_pass http://client:80/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # Отправка и кеширование статических файлов
        location ~* \.(js|css|png|jpg|jpeg|webm|gif|mp3|mp4|ogg|ico|svg|woff|woff2|eot|ttf|otf|map|webp|avif|json|xml|wasm)$ {
            proxy_read_timeout 1m;
            proxy_connect_timeout 1m;
            proxy_send_timeout 1m;

            expires 1y;
            add_header Cache-Control "public, immutable";
            proxy_pass http://client:80;
        }

        # Основной контент (клиентское приложение)
        location / {
            proxy_read_timeout 1m;
            proxy_connect_timeout 1m;

            rewrite ^ / break;
            proxy_pass http://client:80;
        }

        # Обработка ошибок
        error_page 404 /index.html;
        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
